const Database=require('better-sqlite3');const fs=require('fs');const path=require('path');
function openDatabase(file=path.join(process.env.DATA_DIR||'data','banking-reform-tracker.db')){fs.mkdirSync(path.dirname(file),{recursive:true});const db=new Database(file);db.pragma('journal_mode = WAL');db.pragma('foreign_keys = ON');migrate(db);return db}
function migrate(db){db.exec(`CREATE TABLE IF NOT EXISTS admin_users(id INTEGER PRIMARY KEY,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,must_change_password INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS timer_configuration(id INTEGER PRIMARY KEY CHECK(id=1),reference_date TEXT NOT NULL,timezone TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'monitoring' CHECK(status IN ('monitoring','under_discussion','officially_implemented')),is_running INTEGER NOT NULL DEFAULT 1,implementation_date TEXT,decision_note TEXT,official_source_url TEXT,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS blog_posts(id INTEGER PRIMARY KEY,title TEXT NOT NULL,slug TEXT UNIQUE NOT NULL,summary TEXT NOT NULL,content TEXT NOT NULL,category TEXT NOT NULL,tags TEXT DEFAULT '[]',source_name TEXT,source_url TEXT,related_entities TEXT DEFAULT '[]',status TEXT NOT NULL DEFAULT 'pending_review',origin TEXT NOT NULL DEFAULT 'manual',published_at TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS news_articles(id INTEGER PRIMARY KEY,title TEXT NOT NULL,canonical_url TEXT UNIQUE NOT NULL,snippet TEXT,source_name TEXT,retrieved_at TEXT NOT NULL,keyword_score INTEGER DEFAULT 0,raw_metadata TEXT);
CREATE TABLE IF NOT EXISTS scraper_sources(id INTEGER PRIMARY KEY,name TEXT NOT NULL,url TEXT UNIQUE NOT NULL,type TEXT NOT NULL,enabled INTEGER DEFAULT 1,last_checked_at TEXT);
CREATE TABLE IF NOT EXISTS scraper_runs(id INTEGER PRIMARY KEY,status TEXT NOT NULL,started_at TEXT NOT NULL,finished_at TEXT,discovered INTEGER DEFAULT 0,drafts INTEGER DEFAULT 0,error TEXT);
CREATE TABLE IF NOT EXISTS system_logs(id INTEGER PRIMARY KEY,level TEXT,event TEXT,message TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS milestones(id INTEGER PRIMARY KEY,title TEXT NOT NULL,description TEXT,status TEXT DEFAULT 'pending',event_date TEXT,is_verified INTEGER DEFAULT 0,source_name TEXT,source_url TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS timeline_events(id INTEGER PRIMARY KEY,title TEXT NOT NULL,description TEXT,event_date TEXT NOT NULL,is_verified INTEGER DEFAULT 0,source_name TEXT,source_url TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS quotes(id INTEGER PRIMARY KEY,quote TEXT NOT NULL,attribution TEXT,active INTEGER DEFAULT 1,origin TEXT DEFAULT 'sample');
CREATE TABLE IF NOT EXISTS resources(id INTEGER PRIMARY KEY,title TEXT NOT NULL,description TEXT,url TEXT NOT NULL,source_name TEXT,resource_type TEXT DEFAULT 'link',is_verified INTEGER DEFAULT 0,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS faqs(id INTEGER PRIMARY KEY,question TEXT NOT NULL,answer TEXT NOT NULL,sort_order INTEGER DEFAULT 0,active INTEGER DEFAULT 1);
CREATE TABLE IF NOT EXISTS tips(id INTEGER PRIMARY KEY,name TEXT,email TEXT,message TEXT NOT NULL,status TEXT DEFAULT 'pending',created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS analytics_events(id INTEGER PRIMARY KEY,event_type TEXT NOT NULL,path TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP);
CREATE INDEX IF NOT EXISTS idx_posts_status_date ON blog_posts(status,published_at);CREATE INDEX IF NOT EXISTS idx_posts_category ON blog_posts(category);CREATE INDEX IF NOT EXISTS idx_news_title ON news_articles(title);CREATE INDEX IF NOT EXISTS idx_milestones_date ON milestones(event_date);CREATE INDEX IF NOT EXISTS idx_tips_status ON tips(status);`);db.prepare(`INSERT OR IGNORE INTO timer_configuration(id,reference_date,timezone) VALUES(1,?,?)`).run('2024-09-04T10:00:00+05:30','Asia/Kolkata')}
module.exports={openDatabase,migrate};
